export const recipes = [
  {
    id: "1",
    name: "Spaghetti with Meatballs",
    cuisine: "Italian-American",
    img: "https://picsum.photos/250/250",
    ingredients: [
      "paghetti",
      "ground beef",
      "breadcrumbs",
      "egg",
      "chopped parsley",
      "milk",
    ],
    instructions: [
      "Cook the spaghetti according to package instructions until al dente.",
      "In a large bowl, combine the ground beef, breadcrumbs, egg, parsley, Parmesan, milk, salt, and pepper. Mix until well combined and form into meatballs.",
      "In a large skillet, heat the olive oil over medium heat. Add the onion and garlic and cook until softened, about 5 minutes.",
      "Add the crushed tomatoes, sugar, and red pepper flakes. Bring to a simmer and add the meatballs. Cover and simmer for 15-20 minutes, until the meatballs are cooked through.",
      "Serve the meatballs and sauce over the cooked spaghetti. Garnish with fresh basil.",
    ],
  },
  {
    id: "2",
    name: "Chicken Stir-Fry",
    cuisine: "Asian",
    img: "https://picsum.photos/250/250",
    ingredients: [
      "boneless, skinless chicken breasts",
      "soy sauce",
      "sesame oil",
      "garlic cloves",
      "ginger",
    ],
    instructions: [
      "Cut the chicken breasts into bite-sized pieces. In a bowl, combine the soy sauce, sesame oil, minced garlic, and grated ginger. Add the chicken pieces and toss to coat. Let it marinate for 15-20 minutes.",
      "Heat vegetable oil in a large skillet or wok over high heat. Add the marinated chicken and stir-fry for 5-6 minutes, until cooked through. Remove the chicken from the skillet and set aside.",
      "In the same skillet, add the broccoli florets, sliced carrots, and bell peppers. Stir-fry for 3-4 minutes, until the vegetables are crisp-tender.",
      "In a small bowl, whisk together cornstarch, chicken broth, and hoisin sauce. Pour the mixture into the skillet with the vegetables. Stir well and cook for 1-2 minutes, until the sauce thickens.",
    ],
  },
  {
    id: "3",
    name: "Caprese Salad",
    cuisine: "Italian",
    img: "https://picsum.photos/250/250",
    ingredients: [
      "ripe tomatoes",
      "fresh mozzarella cheese",
      "fresh basil leaves",
      "extra virgin olive oil",
    ],
    instructions: [
      "Slice the tomatoes and fresh mozzarella cheese into thick slices.",
      "Arrange the tomato and mozzarella slices on a serving platter, alternating between the two.",
      "Place fresh basil leaves on top of each tomato and mozzarella slice.",
      "Drizzle extra virgin olive oil and balsamic vinegar over the salad.",
    ],
  },
];
